### ISSUE TITLE
Works with  DTU-Pro-S ?

### ISSUE THREAD

**Issue by Kybernetes2** [wasilukm/hoymiles-mqtt#11]
Hello,
Do you know if the code also works with the Hoymiles DTU-Pro-S ? The Pro-S looks like the same as the Pro, but its for the Sub-1G frequencies used by the HMS Type from the hoymiles.

And do you know if its possible to set the output power of the hoymile inverters via modbus commands via the DTU Pro?

**Comment by wasilukm** [comment]
I don't have S version, but I'm quite sure I had a feedback that it is also working.

According to modbus spec it should be possible to turn on/off or limit output power of selected panel/port.
