### ISSUE TITLE
[Question] DTU device

### ISSUE THREAD

**Issue by mbrammer** [wasilukm/hoymiles-mqtt#13]
Hello,

the description of the repo says "The tool periodically communicates with Hoymiles DTU (Pro)". The "Pro" in in parentheses. Does this mean it could also work with the lite stick W100?

**Comment by wasilukm** [comment]
Hi
Only Pro is supported and most likely Pro-S (not officially verified)

**Comment by mbrammer** [comment]
Alright :( Maybe you can edit the README, so others don't fall into this as well ;)
