### ISSUE TITLE
null not "0"

### ISSUE THREAD

**Issue by foxos42** [wasilukm/hoymiles-mqtt#19]
* Hoymiles MQTT version: 0.5
* Python version: 3.9
* Operating System: alpine
* Docker: Yes

### Description

Hi,
nice work! I use v0.5 inside a docker container.

If link status is down all data will be send with a "0". This is wrong, because it is not "0". In this case data should be set to "null" or should just not be send.

I push all the data right into a TS-database and "0" is a valid value so I see voltage drops to "0" just because the Inverter was not reachable. But this is apparently not the reality. I have a workaround in place but "0" is just not "null". ;)

### What I Did

Just looked @ the data with mqtt explorer and saw the Issue ;)

**Comment by wasilukm** [comment]
Hi, sorry for not answering for a long time. Your request is similar to #14. I will work on an improvement to not send data without a connection with an inverter.
